### PR TITLE
Update for Latest Rust Nightly

### PR DESCRIPTION
**Pull request by indiv0**
Doesn't fix any deprecation warnings. I'll open a separate PR for them.

### CODE REVIEW

**Comment by indiv0** [comment]
Also, this closes #1.

**Comment by uiri** [comment]
When you miss something, checkout the incomplete commit as a new branch, make the change, amend the commit and rebase the later commits onto the new branch (you can then delete the branch).

I'm not squashing any more of these. It makes the history too confusing to have the imports fixed in 5 different commits interspersed with Box::new and unsigned integer type fixes.

Rebase your existing stuff onto the stuff I collected and pushed and then start using rebase -i to clean up your history. If you accidentally anything, git reflog will give you a list of commit hashes you've checked out so that you can recover.

**Comment by indiv0** [comment]
Sorry, I was rushing a bit trying to get the project up-to-date.

I'll take care of it.

**Comment by indiv0** [comment]
Alright, I've squashed everything (within the PR itself) that could be squashed.

My question is now: what do I do with commits that should be squashed onto commits on the master branch?

The ones I can see would be:

7e778bc7499aaa851a20c02d219a2e08c09481fb -> 645a89ba53caea55898448113f6e4f3109ea899a
a3a4f04c72ceb469895edc65e417446147963430 -> bda17e72d062562563f6dcb3baf25648345307cb
1a890c2548fe00358f17c6a770c1efdf178ad6c6 -> 779795f284cb9d7f1e3f9119bde302b97eab92c3
334344c8df49d7e02c9d042f57013586d8dc2be4 -> 7a9b1cfe4fa9f3a52c64b353de0fd58279c5dcdd
7a9b1cfe4fa9f3a52c64b353de0fd58279c5dcdd -> a7f46de0dbfa88a034364993b0ff7ebc08a11ff7

But since they're already on master, I'd be overriding the repo history in doing so.
What do you think I should do?

**Comment by uiri** [comment]
Feel free to squash onto the commits on master. At this point it is fairly dirty with your changes anyways.

In the future, I'd rather yo uproperly squash before sending a pull req :)

**Comment by indiv0** [comment]
Just to make sure, that should be done on the dev branch on my fork, prior to this PR being pulled, right? If so, won't that cause merge conflicts?

And I'll make sure to do that in the future :)

**Comment by uiri** [comment]
It is a lot easier to look at the changes in categories/series which are doing largely the same thing. If I can do that then I can sign off on your changes and just mark your dev branch as master if doing a `git rebase master` after cleaning up your commits makes things too messy.

**Comment by indiv0** [comment]
Alright then I'll try to get that done tomorrow.

**Comment by indiv0** [comment]
Alright, rebases done. Take a look.

**Comment by indiv0** [comment]
@uiri alright, I've cleaned it up a little more.

**Comment by indiv0** [comment]
@uiri I assume you didn't merge the remainder because of the unwrap calls?

If so, I could rebase that commit up to the top then remove it so that you can merge the remainer and we can close this PR.

I can then open a separate PR to implement proper error handling in those locations and others throughout the code.

**Comment by uiri** [comment]
> @uiri I assume you didn't merge the remainder because of the unwrap calls?

Correct.

> If so, I could rebase that commit up to the top then remove it so that you can merge the remainer and we can close this PR.
> 
> I can then open a separate PR to implement proper error handling in those locations and others throughout the code.

Sounds good to me.

**Pull request merged**
